FROM python:3.8

ENV PYTHONUNBUFFERED 1

WORKDIR /app

RUN apt update
RUN apt install -y joe 
RUN apt install -y redis

COPY contacts/requirements.txt /requirements.txt
RUN pip install -r /requirements.txt

ENV PYTHONPATH /app

