"""empty message

Revision ID: 02c5c7a81f44
Revises: cc05ccfcb65d
Create Date: 2020-11-08 04:42:25.139225

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '02c5c7a81f44'
down_revision = 'cc05ccfcb65d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('created', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('id_user', postgresql.UUID(), nullable=False),
    sa.Column('ttl', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('closed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_active'), 'sessions', ['active'], unique=False)
    op.create_index(op.f('ix_sessions_created'), 'sessions', ['created'], unique=False)
    op.create_index(op.f('ix_sessions_id_user'), 'sessions', ['id_user'], unique=False)
    op.add_column('users', sa.Column('permission_flags', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'permission_flags')
    op.drop_index(op.f('ix_sessions_id_user'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_created'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_active'), table_name='sessions')
    op.drop_table('sessions')
    # ### end Alembic commands ###
