"""test

Revision ID: 246dcc203f57
Revises: 02c5c7a81f44
Create Date: 2020-11-10 21:07:56.892921

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '246dcc203f57'
down_revision = '02c5c7a81f44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forgot_password_ids',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('created', sa.TIMESTAMP(), nullable=True),
    sa.Column('id_user', postgresql.UUID(), nullable=False),
    sa.Column('expired', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forgot_password_ids_created'), 'forgot_password_ids', ['created'], unique=False)
    op.create_index(op.f('ix_forgot_password_ids_expired'), 'forgot_password_ids', ['expired'], unique=False)
    op.create_index(op.f('ix_forgot_password_ids_id_user'), 'forgot_password_ids', ['id_user'], unique=False)
    op.add_column('users', sa.Column('active', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email')
    op.drop_column('users', 'active')
    op.drop_index(op.f('ix_forgot_password_ids_id_user'), table_name='forgot_password_ids')
    op.drop_index(op.f('ix_forgot_password_ids_expired'), table_name='forgot_password_ids')
    op.drop_index(op.f('ix_forgot_password_ids_created'), table_name='forgot_password_ids')
    op.drop_table('forgot_password_ids')
    # ### end Alembic commands ###
