"""init

Revision ID: d17dcc9b412e
Revises: 
Create Date: 2020-11-10 21:24:19.220960

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd17dcc9b412e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('created', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('permission_flags', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_created'), 'users', ['created'], unique=False)
    op.create_table('forgot_password_ids',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('created', sa.TIMESTAMP(), nullable=True),
    sa.Column('id_user', postgresql.UUID(), nullable=False),
    sa.Column('expired', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forgot_password_ids_created'), 'forgot_password_ids', ['created'], unique=False)
    op.create_index(op.f('ix_forgot_password_ids_expired'), 'forgot_password_ids', ['expired'], unique=False)
    op.create_index(op.f('ix_forgot_password_ids_id_user'), 'forgot_password_ids', ['id_user'], unique=False)
    op.create_table('sessions',
    sa.Column('created', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('id_user', postgresql.UUID(), nullable=False),
    sa.Column('ttl', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('closed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_active'), 'sessions', ['active'], unique=False)
    op.create_index(op.f('ix_sessions_created'), 'sessions', ['created'], unique=False)
    op.create_index(op.f('ix_sessions_id_user'), 'sessions', ['id_user'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_id_user'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_created'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_active'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_forgot_password_ids_id_user'), table_name='forgot_password_ids')
    op.drop_index(op.f('ix_forgot_password_ids_expired'), table_name='forgot_password_ids')
    op.drop_index(op.f('ix_forgot_password_ids_created'), table_name='forgot_password_ids')
    op.drop_table('forgot_password_ids')
    op.drop_index(op.f('ix_users_created'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
